use dataluta_db;

DELIMITER $$
CREATE PROCEDURE cadastroConta(sp_CODLOCAL INT, sp_NOME VARCHAR(100), sp_MUNICIPIO VARCHAR(50), sp_UF VARCHAR(20), sp_NOMEASSENTAMENTO VARCHAR(50), sp_EMAIL VARCHAR(50), sp_SENHA VARCHAR(50))
BEGIN
    INSERT INTO USUARIO (CODLOCAL, NOME, MUNICIPIO, UF, NOMEASSENTAMENTO, EMAIL, SENHA) VALUES (sp_CODLOCAL, sp_NOME, sp_MUNICIPIO, sp_UF, sp_NOMEASSENTAMENTO, sp_EMAIL, sp_SENHA);
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE cadastrarProducao(sp_CODPRODUCAO INT, sp_DATAINI DATE, sp_DATAFIN DATE, sp_QUALIDADE VARCHAR(50), sp_QUANTIDADE INT, sp_TIPOPRODUCAO VARCHAR(50), CATEGORIA VARCHAR(50))
BEGIN
    INSERT INTO PRODUCAO (CODPRODUCAO, DATAINI, DATAFIN, QUALIDADE, QUANTIDADE, TIPO) VALUES (sp_CODPRODUCAO, sp_DATAINI, sp_DATAFIN, sp_QUALIDADE, sp_QUANTIDADE, sp_TIPOPRODUCAO, CATEGORIA);
END $$
DELIMITER ;
